In [1]:
import os,django
import pandas as pd
from orm.models import Siswa,Kelas,Karakter,HasilTes,NilaiAkademik,Plomba,TesOlimpiade,Bobot
import math
from django.contrib.auth.models import User

In [26]:
tp =TesOlimpiade.objects.all()
sw = Siswa.objects.all()
user = User.objects.all()
ht = HasilTes.objects.all()

In [30]:
def ListDatauser(user):
    us=User.objects.all()
    if len(us)>0:
        cols = ['id']
        dt ={
            cols[0] : [str(a.username) for a in us],
            
        }
        dfdata_siswa = pd.DataFrame(data=dt)
        return dfdata_siswa
    else:
        return[]
ListDatauser(user)

                    id
0       gora@gmail.com
1     sagita@gmail.com
2     satria@gmail.com
3      azura@gmail.com
4    afriani@gmail.com
5       reza@gmail.com
6        dio@gmail.com
7      desak@gmail.com
8    binazir@gmail.com
9       made@gmail.com
10              admin1
11  yunuslon@gmail.com

In [20]:
def ListDataSiswa(sw):
    if len(sw)>0:
        cols = ['id','username','siswa','alamat','mata_pelajaran','nilai_akademik','jenjang',
               'sikap','intensitas']
        
        dt ={
            cols[0] : [int(a.id) for a in sw],
            cols[1] : [str(a.user)  for a in sw],
            cols[2] : [str(a.nama) for a in sw],
            cols[3] : [str(a.alamat) for a in sw],
            cols[4] : [str(a.nilai_akademiks.mata_pelajaran) for a in sw],
            cols[5] : [int(a.nilai_akademiks.nilai) for a in sw],
            cols[6] : [str(a.kelass.jenjang) for a in sw],
            cols[7] : [str(a.karakters.sikap) for a in sw],
            cols[8] : [str(a.plombas.intensitas) for a in sw],
        }
        dfdata_siswa = pd.DataFrame(data=dt)
        return dfdata_siswa
    else:
        return[]

def ListDatauser(user):
    us=User.objects.all()
    if len(us)>0:
        cols = ['id']
        dt ={
            cols[0] : [str(a.username) for a in us],
            
        }
        dfdata_siswa = pd.DataFrame(data=dt)
        return dfdata_siswa
    else:
        return[]
ListDataSiswa(sw)

,id,username,siswa,alamat,mata_pelajaran,nilai_akademik,jenjang,sikap,intensitas
0,2,gora@gmail.com,Gora Wahyu,Taman Baru,biologi,90,2 SMA,Baik,Sering Mengikuti Olimpiade
1,3,sagita@gmail.com,Sagita Putri,Pabutan Permai,biologi,90,3 SMA,Baik,Sering Mengikuti Olimpiade
2,4,satria@gmail.com,Satria Wira,Moncok,biologi,90,3 SMA,Baik,Sering Mengikuti Olimpiade
3,12,azura@gmail.com,Azura fransisca,Perumnas,biologi,87,1 SMA,Cukup Baik,Cukup Sering Mengikuti Olimpiade
4,13,afriani@gmail.com,Afriani Ibrahim Putri,Taman sari,biologi,88,2 SMA,Baik,Sering Mengikuti Olimpiade
5,14,reza@gmail.com,Reza Rahmanto,Pondok Perasi,fisika,90,2 SMA,Baik,Sering Mengikuti Olimpiade
6,15,dio@gmail.com,Oktadio Erikardo,Taman Baru,fisika,87,3 SMA,Baik,Cukup Sering Mengikuti Olimpiade
7,16,desak@gmail.com,I Desak Puspita Sari,Gebang,fisika,89,1 SMA,Baik,Cukup Sering Mengikuti Olimpiade
8,17,binazir@gmail.com,Binazir silvia,Pejeruk Bangket,fisika,86,3 SMA,Cukup Baik,Cukup Sering Mengikuti Olimpiade
9,18,made@gmail.com,I MadeRandiawan,Monjok,fisika,90,2 SMA,Cukup Baik,Jarang Mengikuti Olimpiade

In [12]:
def SlkIdBio(sw):
    c= ListDataSiswa(sw)
    tmpA=list(zip(c.mata_pelajaran,c.username))
    tmp=[]
    for i in range(len(c)):
        if tmpA[i][0] == "biologi":
            tmp.append(tmpA[i][1])
    df=pd.DataFrame(data=tmp,columns=['Username'])
    return df
SlkIdBio(sw)

AttributeError: 'Siswa' object has no attribute 'user_password'

In [3]:
def ListTesOlimpiade(tp):
    if len(tp)>0:
        cols = ['mata_pelajaran','no','gambar','pertayaan',
                'jawabanA','jawabanB','jawabanC','jawabanD','jawabanE','kunci','id']
        
        topd ={
            cols[0] : [str(a.mata_pelajaran) for a in tp],
            cols[1] : [int(a.no) for a in tp],
            cols[2] : [str(a.gambar) for a in tp],
            cols[3] : [str(a.pertayaan) for a in tp],
            cols[4] : [str(a.jawabanA) for a in tp],
            cols[5] : [str(a.jawabanB) for a in tp],
            cols[6] : [str(a.jawabanC) for a in tp],
            cols[7] : [str(a.jawabanD) for a in tp],
            cols[8] : [str(a.jawabanE) for a in tp],
            cols[9] : [str(a.kunci) for a in tp],
            cols[10] : [str(a.id) for a in tp],
        }
        dfmt = pd.DataFrame(data=topd)
        return dfmt
    else:
        return[]

In [6]:
def soal_id_bio(tp):
    c= ListTesOlimpiade(tp)
    tmpA=list(zip(c.mata_pelajaran,c.no,c.gambar,c.pertayaan,
                  c.jawabanA,c.jawabanB,c.jawabanC,c.jawabanD,c.jawabanE,c.kunci,c.id))
    tmp=[]
    for i in range(len(c)):
        if tmpA[i][0] == "biologi":
            tmp.append(tmpA[i][10])
    df=pd.DataFrame(data=tmp, columns=['ID'])
    return df

In [14]:
def SleksiSoalBio():
    c= ListTesOlimpiade(tp)
    tmpA=list(zip(c.mata_pelajaran,c.no,c.gambar,c.pertayaan,
                  c.jawabanA,c.jawabanB,c.jawabanC,c.jawabanD,c.jawabanE,c.kunci,c.id))
    def id_soal():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][10])
        df=pd.DataFrame(data=tmp, columns=['id'])
        return df
    
    def no():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][1])
        df=pd.DataFrame(data=tmp, columns=['No'])
        return df

    def gambar():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][2])
        df=pd.DataFrame(data=tmp, columns=['Gambar'])
        return df
    
    def pertayaan():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][3])
        df=pd.DataFrame(data=tmp, columns=['Pertayaan'])
        return df

    def jawabanA():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][4])
        df=pd.DataFrame(data=tmp, columns=['JawabanA'])
        return df

    def jawabanB():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][5])
        df=pd.DataFrame(data=tmp, columns=['JawabanB'])
        return df

    def jawabanC():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][6])
        df=pd.DataFrame(data=tmp, columns=['JawabanC'])
        return df

    def jawabanD():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][7])
        df=pd.DataFrame(data=tmp, columns=['JawabanD'])
        return df

    def jawabanE():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][8])
        df=pd.DataFrame(data=tmp, columns=['JawabanE'])
        return df
    
    def kunci():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "biologi":
                tmp.append(tmpA[i][9])
        df=pd.DataFrame(data=tmp, columns=['Kunci'])
        return df
    
    gabung= pd.concat([id_soal(),no(),gambar(),pertayaan(),jawabanA(),jawabanB(),jawabanC(),jawabanD(),jawabanE(),kunci()],
                      axis=1)

    return gabung

SleksiSoalBio()

,id,No,Gambar,Pertayaan,JawabanA,JawabanB,JawabanC,JawabanD,JawabanE,Kunci
0,1,1,../media/gambar/a.png,Berikut ini adalah ciri yang dimiliki fauna kh...,banyak Mammalia berukuran besar,terdapat berbagai macam spesies kera,terdapat berbagai macam burung berbulu indah,sedikit hewan berkantung,banyak hewan primata,C
1,2,2,../media/gambar/a.png,Penggolongan organisme dengan menggunakan klas...,habitat,habitat dan morfologi,ciri bentuk luar tubuh,kekerabatan secara evolusi,habitus (perawakan),C
2,3,3,gambar/urin.png,"Salah satu proses pembentukan urin, terjadi pr...",1,2,3,4,5,D
3,4,4,gambar/Pertumbuhanperkembangan.png,Dua kecambah kacang hijau diletakkan di suatu ...,cahaya merupakan faktor yang tidak dibutuhkan ...,pertumbuhan kecambah tidak memerlukan cahaya,cahaya sangat mempengaruhi pertumbuhan kecambah.,cahaya diperlukan dalam jumlah sedikit untuk p...,cahaya dapat menghambat pertumbuhan kecambah.,E
4,5,5,../media/gambar/a.png,Molekul tRNA merupakan jenis RNA yang terdapat...,membentuk pita tunggal RNA yang akan ditranskr...,mengirimkan informasi genetik ke dalam ribosom.,membawa asam amino hasil translasi.,menerjemahkan asam amino yang akan dibentuk.,membantu DNA untuk mensintesis kodon.,C

In [6]:
def SleksiSoalFis():
    c= ListTesOlimpiade(tp)
    tmpA=list(zip(c.mata_pelajaran,c.no,c.gambar,c.pertayaan,
                  c.jawabanA,c.jawabanB,c.jawabanC,c.jawabanD,c.jawabanE,c.kunci))
    def no():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][1])
        df=pd.DataFrame(data=tmp, columns=['No'])
        return df

    def gambar():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][2])
        df=pd.DataFrame(data=tmp, columns=['Gambar'])
        return df
    
    def pertayaan():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][3])
        df=pd.DataFrame(data=tmp, columns=['Pertayaan'])
        return df

    def jawabanA():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][4])
        df=pd.DataFrame(data=tmp, columns=['JawabanA'])
        return df

    def jawabanB():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][5])
        df=pd.DataFrame(data=tmp, columns=['JawabanB'])
        return df

    def jawabanC():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][6])
        df=pd.DataFrame(data=tmp, columns=['JawabanC'])
        return df

    def jawabanD():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][7])
        df=pd.DataFrame(data=tmp, columns=['JawabanD'])
        return df

    def jawabanE():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][8])
        df=pd.DataFrame(data=tmp, columns=['JawabanE'])
        return df
    
    def kunci():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "fisika":
                tmp.append(tmpA[i][9])
        df=pd.DataFrame(data=tmp, columns=['Kunci'])
        return df
    
    gabung= pd.concat([no(),gambar(),pertayaan(),jawabanA(),jawabanB(),jawabanC(),jawabanD(),jawabanE(),kunci()],
                      axis=1)

    return gabung

In [19]:
def SleksiSoalKim():
    c= ListTesOlimpiade(tp)
    tmpA=list(zip(c.mata_pelajaran,c.no,c.gambar,c.pertayaan,
                  c.jawabanA,c.jawabanB,c.jawabanC,c.jawabanD,c.jawabanE,c.kunci))
    def no():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][1])
        df=pd.DataFrame(data=tmp, columns=['No'])
        return df

    def gambar():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][2])
        df=pd.DataFrame(data=tmp, columns=['Gambar'])
        return df
    
    def pertayaan():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][3])
        df=pd.DataFrame(data=tmp, columns=['Pertayaan'])
        return df

    def jawabanA():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][4])
        df=pd.DataFrame(data=tmp, columns=['JawabanA'])
        return df

    def jawabanB():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][5])
        df=pd.DataFrame(data=tmp, columns=['JawabanB'])
        return df

    def jawabanC():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][6])
        df=pd.DataFrame(data=tmp, columns=['JawabanC'])
        return df

    def jawabanD():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][7])
        df=pd.DataFrame(data=tmp, columns=['JawabanD'])
        return df

    def jawabanE():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][8])
        df=pd.DataFrame(data=tmp, columns=['JawabanE'])
        return df
    
    def kunci():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "kimia":
                tmp.append(tmpA[i][9])
        df=pd.DataFrame(data=tmp, columns=['Kunci'])
        return df
    
    gabung= pd.concat([no(),gambar(),pertayaan(),jawabanA(),jawabanB(),jawabanC(),jawabanD(),jawabanE(),kunci()],
                      axis=1)

    return gabung

In [ ]:
def SleksiSoalMat():
    c= ListTesOlimpiade(tp)
    tmpA=list(zip(c.mata_pelajaran,c.no,c.gambar,c.pertayaan,
                  c.jawabanA,c.jawabanB,c.jawabanC,c.jawabanD,c.jawabanE,c.kunci))
    def no():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][1])
        df=pd.DataFrame(data=tmp, columns=['No'])
        return df

    def gambar():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][2])
        df=pd.DataFrame(data=tmp, columns=['Gambar'])
        return df
    
    def pertayaan():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][3])
        df=pd.DataFrame(data=tmp, columns=['Pertayaan'])
        return df

    def jawabanA():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][4])
        df=pd.DataFrame(data=tmp, columns=['JawabanA'])
        return df

    def jawabanB():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][5])
        df=pd.DataFrame(data=tmp, columns=['JawabanB'])
        return df

    def jawabanC():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][6])
        df=pd.DataFrame(data=tmp, columns=['JawabanC'])
        return df

    def jawabanD():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][7])
        df=pd.DataFrame(data=tmp, columns=['JawabanD'])
        return df

    def jawabanE():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][8])
        df=pd.DataFrame(data=tmp, columns=['JawabanE'])
        return df
    
    def kunci():
        tmp=[]
        for i in range(len(c)):
            if tmpA[i][0] == "matematika":
                tmp.append(tmpA[i][9])
        df=pd.DataFrame(data=tmp, columns=['Kunci'])
        return df
    
    gabung= pd.concat([no(),gambar(),pertayaan(),jawabanA(),jawabanB(),jawabanC(),jawabanD(),jawabanE(),kunci()],
                      axis=1)

    return gabung